version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ali-db
    environment:
      POSTGRES_DB: ali
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ali"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ali-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # mode dev
      NODE_ENV: development
      PORT: 8080
      DATABASE_SSL: "false"

      # JWT & auth
      JWT_SECRET: super_dev_secret_change_me
      JWT_EXPIRES_IN: 7d

      # penting: host db pakai nama service "db", bukan localhost
      DATABASE_URL: postgres://postgres:postgres@db:5432/ali

      # CORS harus mengizinkan origin frontend
      CORS_ORIGINS: http://localhost:5173

      # ML service (opsional, bisa kamu sesuaikan)
      ML_ENABLE: "true"
      ML_BASE_URL: http://127.0.0.1:8000
      ML_TIMEOUT_MS: "5000"
      ML_API_KEY: ""
    ports:
      - "8080:8080"
    volumes:
      # mount source code supaya bisa live reload kalau kamu edit
      - ./backend:/usr/src/app
      # tapi node_modules tetap pakai dari image, bukan dari host
      - /usr/src/app/node_modules
    # Jalankan migrasi + ingest ML + mapping user ML otomatis saat container start
    command: >
      sh -c "npm run ml:bootstrap &&
             npm run import:ml-users &&
             npm run dev"
    # CMD utama sudah diset di Dockerfile:
    # npm run migrate:latest && npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ali-frontend
    depends_on:
      - backend
    environment:
      # FE akan memanggil backend di host ini
      VITE_API_URL: http://localhost:8080
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    # CMD utama sudah diset di Dockerfile:
    # npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  db_data:
